# name: preview-docs
# on: pull_request

# jobs:
#   preview-docs:
#     runs-on: ubuntu-latest
#     permissions: write-all
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Install Fern
#         run: npm install -g fern-api

#       - name: Generate preview URL
#         id: generate-docs
#         env:
#           FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
#         run: |
#           # Run fern generate and capture all output to handle errors gracefully
#           OUTPUT=$(fern generate --docs --preview 2>&1) || true
#           echo "$OUTPUT"

#           # Attempt to extract the preview URL from the OUTPUT if successful
#           # Typically, when success occurs, "Published docs to ..." line is printed
#           URL=$(echo "$OUTPUT" | grep -oP 'Published docs to \K.*(?= \()')

#           echo "Preview URL: $URL"
#           echo "🌿 Preview your docs: $URL" > preview_url.txt

#       - name: Comment URL in PR
#         uses: thollander/actions-comment-pull-request@v2.4.3
#         with:
#           filePath: preview_url.txt
